areas:
- categories:
  - id: 1
    name: 规划
    range:
    - 10.001
    - 10.099
  - id: 2
    name: 执行
    range:
    - 10.1
    - 10.199
  id: 10
  name: 项目
- categories:
  - id: 1
    name: 阅读
    range:
    - 20.001
    - 20.099
  - id: 2
    name: 实践
    range:
    - 20.1
    - 20.199
  id: 20
  name: 学习
user_prefix: HANK
